[package]
name = "testing"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
edition = "2018"

[dependencies]
bootloader = "0.5.0"
x86_64 = "0.5.3"
spin = "0.4.9"
uart_16550 = "0.1.0"

[package.metadata.bootimage]
default-target = "x86_64-testing.json"