[package]
name = "default-target-bootimage"
version = "0.1.0"
authors = ["Philipp Oppermann <dev@phil-opp.com>"]
edition = "2018"

[dependencies]
bootloader = "0.5.0"
x86_64 = "0.5.3"

[package.metadata.bootimage]
default-target = "../x86_64-bootimage-example-kernels.json"